import Foundation

/// Reads `VehicleCatalog.json` from the app bundle once and keeps it in memory.
///
/// The file is generated by `tools/vehicle-catalog/build_catalog.py` — edit the script, not
/// the JSON. ~120 KB, so decoding on first use is cheap and happens off the main actor.
actor BundledVehicleCatalog: VehicleCatalogProviding {
    private let url: URL?
    private var cached: VehicleCatalog?

    init(bundle: Bundle = .main, resource: String = "VehicleCatalog") {
        self.url = bundle.url(forResource: resource, withExtension: "json")
    }

    func catalog() async throws -> VehicleCatalog {
        if let cached { return cached }
        guard let url else {
            throw DomainError.persistence(.readFailed("VehicleCatalog.json is missing from the bundle"))
        }
        do {
            let decoded = try JSONDecoder().decode(VehicleCatalog.self, from: Data(contentsOf: url))
            cached = decoded
            return decoded
        } catch {
            throw DomainError.persistence(.readFailed("VehicleCatalog.json: \(error)"))
        }
    }
}

/// A fixed catalog for tests and previews.
struct StaticVehicleCatalog: VehicleCatalogProviding {
    let value: VehicleCatalog
    func catalog() async throws -> VehicleCatalog { value }
}
